import UserService from "@repo/services/user";
import OrganizationService from "@repo/services/organization";
import MembershipService from "@repo/services/membership";
import FeatureRequestService from "@repo/services/feature-request";
import ProjectService from "@repo/services/project";
import RepositoryService from "@repo/services/repository";
import PrdService from "@repo/services/prd";
import TaskService from "@repo/services/task";
import PullRequestService from "@repo/services/pull-request";
import ReviewService from "@repo/services/review";
import ApprovalService from "@repo/services/approval";
import ReleaseService from "@repo/services/release";
import BillingService from "@repo/services/billing";
import WebhookService from "@repo/services/webhook";
import WorkflowService from "@repo/services/workflow";

export const userService = new UserService();
export const organizationService = new OrganizationService();
export const membershipService = new MembershipService();
export const featureRequestService = new FeatureRequestService();
export const projectService = new ProjectService();
export const repositoryService = new RepositoryService();
export const prdService = new PrdService();
export const taskService = new TaskService();
export const pullRequestService = new PullRequestService();
export const reviewService = new ReviewService();
export const approvalService = new ApprovalService();
export const releaseService = new ReleaseService();
export const billingService = new BillingService();
export const webhookService = new WebhookService();
export const workflowService = new WorkflowService();
